### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by jkirk** [jkirk/kthresher#2]
`kthresher` does not seem to support Python 3:
```
% sudo apt install python3-apt python3-setuptools python3-wheel
% sudo apt install python3-pip
% sudo pip3 install git+https://github.com/rackerlabs/kthresher.git 
Collecting git+https://github.com/rackerlabs/kthresher.git
  Cloning https://github.com/rackerlabs/kthresher.git to /tmp/pip-req-build-c5dca1re
Building wheels for collected packages: kthresher
  Running setup.py bdist_wheel for kthresher ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-gxz1n3zz/wheels/42/5f/47/81ed8fa28f051cc1134f97e23e6fea7de3822d9a6edfac37ba
Successfully built kthresher
Installing collected packages: kthresher
Successfully installed kthresher-1.3.1

% kthresher --help
Traceback (most recent call last):
  File "/usr/local/bin/kthresher", line 11, in <module>
    load_entry_point('kthresher==1.3.1', 'console_scripts', 'kthresher')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/grml/.local/lib/python3.7/site-packages/kthresher.py", line 39, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

There is also an upstream issue (rackerlabs/kthresher#53) regarding Python 3 support.

**Comment by jkirk** [comment]
Fixed upstream.
